[package]
name = "manager"
version = "0.1.0"
authors = ["siul"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared" }
brotli = "3.3.0"
tar = "0.4"
blake3 = "0.3.3"